class AnalystBrain:
    OUT_PATH = "data/marts/product_day_facts.parquet"
    def __init__(self, sales: SalesBrain, insta: InstaBrain): ...
    def refresh_mart(self) -> str: ...
    def analyze(self, product_id: str, start: str, end: str, question: str) -> dict: ...