class SalesBrain:
    FACTS_PATH = "data/marts/sales_facts.parquet"
    def ingest_file(self, src_path: str, period: str) -> str: ...
    def build_features(self, overwrite=False) -> str: ...
    def query(self, product_id: str|None, start: str, end: str): ...